### ISSUE TITLE
caniuse

### ISSUE THREAD

**Issue by o-jasper** [aharris88/awesome-cli#1]
> "Can I use" provides up-to-date browser support tables for support of front-end web technologies on desktop and mobile web browsers.

So that line to something like "query caniuse.com if browser supports something"? As-is the line doesnt provide a little description.

**Comment by aharris88** [comment]
I'm not quite sure what you're saying... Where are you quoting that from? In my list it just says:

    caniuse-cmd- Caniuse command line tool

**Comment by o-jasper** [comment]
Oh i just mean is that the description doesnt give any information, realy. Suggest:

    caniuse-cmd- queries caniuse.com about browser support of feature

**Comment by aharris88** [comment]
Oh yeah, I've just been grabbing the description from the original repo. Good point though.
